export const GET_LICENSES = 'GET_LICENSES';
export const POST_LICENSE = 'POST_LICENSE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_LICENSE_ONLINE = 'SET_LICENSE_ONLINE';
export const DELETE_LICENSE = 'DELETE_LICENSE';
export const GET_LICENSE_MEDIA = 'GET_LICENSE_MEDIA';
export const SET_IS_LOADING_MEDIA = 'SET_IS_LOADING_MEDIA';
